apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::610996732950:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-SwgBxUamDP86
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::610996732950:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-24T18:14:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "145133"
  uid: 2d0bf9c6-439d-4309-9996-2f2d02737836
